import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navigation } from "./components/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-slate-900 text-white p-4 text-center">
            {/* <p>Welcome to Next.js 15 Crash Course</p> */}
            <Navigation />
          </header>
        {children} 
        <footer className="bg-slate-900 text-white p-4 text-center">
            Codevolution
          </footer>
      </body>
    </html>
  );
}

{/* Here "Childern" prop represents the page content which Next.js will automatically populate based on the current route, home component for the root route, about component for about route and so on. */}